#!/usr/bin/env Rscript

# Compatibility wrapper retained for the original feature-importance script name.
# The cleaned workflow uses code/random_forest.py and code/randomforest.txt.

message("Feature importance is generated by code/random_forest.py. Please run: bash code/randomforest.txt")

